FROM node:20

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build -- --configuration production

RUN npm install -g http-server

# Rename index.csr.html to index.html
RUN mv /app/dist/frontend-angular/browser/index.csr.html /app/dist/frontend-angular/browser/index.html

WORKDIR /app/dist/frontend-angular/browser
EXPOSE 3133
CMD ["http-server", "-p", "3133", "-c-1", "--proxy", "http://localhost?", "--fallback", "index.html"]
